name: nodejs
description: 'Node.js application'
displayName: Node.js Runtime
icon: https://doyensec.com/img/doyensec-logo.svg
versions:
  - version: 2.2.1
    default: true # should have one and only one default version
